root: ./

redirects:
  out-of-band: ./
  desktop-welcome: ./guides/using-the-desktop-app/README.md
  desktop-help: ./guides/using-the-desktop-app/features.md
  desktop-https: ./
  connect-mac: ./guides/control-your-computer-remotely-mac-to-mac.md
  connect-windows: ./guides/applications/remote-graphical-desktop-access/control-your-windows-device-remotely-windows-to-windows/README.md
  connect-rpi: ./making-connections.md
  connect-linux: ./guides/using-the-desktop-app/peer-to-peer-connections.md
  minecraft: ./guides/hosting-a-minecraft-server.md
  platforms/quick-start-on-raspberry-pi/setup-your-raspberry-pi: ./platforms/quick-start-on-raspberry-pi.md
  platforms/quick-start-on-raspberry-pi/install-remote.it: ./adding-remote.it-to-your-device/the-remoteit-package-for-raspbian.md
